# Generated by Django 2.2.7 on 2020-10-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201020_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='register',
            name='Gender',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
